[book]
title = "skry documentation"
authors = ["Ender KUŞ"]
language = "en"
src = "src"

[output.html]
site-url = "/skry/docs/en/"
git-repository-url = "https://github.com/enderkus/skry"
edit-url-template = "https://github.com/enderkus/skry/edit/main/book/en/src/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
additional-js = ["lang.js"]
additional-css = ["extra.css"]

[output.html.search]
enable = true
